# Site settings
title: MyWays
description: On this sites, I will show you how other and I do some awesome things. On the one hand can you explore MyThemeWay. I present you there the jekyll themes Dark- and Light-Particle. On the other hand can you dive into MyVimWay. I will introduce you there how I use Vim and a vim-like behavior in tmux and Zsh. In the future, will be some other cool stuff be added. So be curious what will come.
encoding: utf-8
markdown: kramdown
future: true # allow posts with future dates

# User settings
username: Sitdisch
user_picture: "/assets/img/User_picture.png"
email: sitdisch@gmx.de
github_username: sitdisch
youtube_channel_id: UCMFn6ns1rZarJ9YdVI0n2Zg
twitter_username: sitdisch
linkedin_username: # your_linkedin_username
facebook_username: # your_facebook_username
instagram_username: # your_instagram_username

# Google-analytics
google_site_verification: A5hFTdxUW8tb3SxXwn-yxxzTPAvUF6KA7f8goqiiBoA

exclude: ['package.json', 'src' , 'node_modules']

plugins:
  - github-pages
