name: Lighthouse Check

on:
  page_build:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: 'sitdisch/cloud'
        persist-credentials: false
    - uses: actions/checkout@master
      with:
        repository: 'mythemeway/lighthouse-badges'
        persist-credentials: false
        path: nested
    - name: Create Results
      run: |
        cd nested
        export LIGHTHOUSE_BADGES_PARAMS="--throttling.cpuSlowdownMultiplier=2"
        ./src/index.js -u https://sitdisch.github.io https://sitdisch.github.io/mythemeway/2020/11/01/dark-particle.html https://sitdisch.github.io/mythemeway/2020/11/01/light-particle.html https://sitdisch.github.io/privacy-policy.html -r -b plastic -o sitdisch/mobile
        export LIGHTHOUSE_BADGES_PARAMS="--preset=desktop --throttling.cpuSlowdownMultiplier=1"
        ./src/index.js -u https://sitdisch.github.io https://sitdisch.github.io/mythemeway/2020/11/01/dark-particle.html https://sitdisch.github.io/mythemeway/2020/11/01/light-particle.html https://sitdisch.github.io/privacy-policy.html -r -b plastic -o sitdisch/desktop
        cp -r sitdisch ../lighthouse-results/
        cd ..
    - name: Commit Results
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lighthouse-results/sitdisch
        git commit -am "Lighthouse Results Refreshed | Sitdisch"
    - name: Push Results
      uses: ad-m/github-push-action@master
      with:
        repository: 'sitdisch/cloud'
        github_token: ${{ secrets.SITDISCH_REPO_TOKEN }}

# RESIDUUM
#
# USE OF FOO-SOFTWARE/LIGHTHOUSE-CHECK-ACTION@MASTER
# on:
#   page_build:
#   schedule:
#     - cron: '55 0 * * *'
# jobs:
#   lighthouse-check:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - run: mkdir /tmp/artifacts
#       - name: Run Lighthouse
#         uses: foo-software/lighthouse-check-action@master
#         with:
#           emulatedFormFactor: "desktop"
#           outputDirectory: /tmp/artifacts
#           urls: 'https://mytestdummy.github.io,https://mytestdummy.github.io/projects/2020/10/31/project-1.html,https://mytestdummy.github.io/projects/2020/10/31/project-2.html'
#       - name: Upload artifacts
#         uses: actions/upload-artifact@master
#         with:
#           name: Lighthouse reports
#           path: /tmp/artifacts
# name: Lighthouse Check

# on:
#   page_build:
#   schedule:
#     - cron: '55 0 * * *'

# jobs:
#   lighthouse-check:
#     runs-on: ubuntu-latest
#     steps:
#       - run: npm install @emazzotta/lighthouse-badges@1.1.4
#       - run: npm i -g lighthouse-badges lighthouse-badges --urls https://www.mytestdummy.github.io -o test_results
#       - name: Upload artifacts
#         uses: actions/upload-artifact@master
#         with:
#           name: Lighthouse Results
#           path: /tmp/artifacts
